# Generated by Django 5.0 on 2024-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0002_remove_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cienca_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="curiosidades_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="espiritualidad_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="geopolitica_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="historia_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sociedad_score",
            field=models.IntegerField(default=0),
        ),
    ]
