# Generated by Django 4.2.9 on 2024-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0003_userprofile_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fails_avg",
            field=models.IntegerField(default=0),
        ),
    ]
