# Generated by Django 5.0 on 2024-01-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0003_userprofile_cienca_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="cienca_score",
            new_name="ciencia_score",
        ),
    ]
