# Generated by Django 4.2.9 on 2024-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0005_userprofile_informatica_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuadro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuadro", models.CharField(max_length=500)),
                ("autor", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("description", models.CharField(max_length=10000)),
                ("A", models.CharField(max_length=200)),
                ("B", models.CharField(max_length=200)),
                ("C", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=400)),
            ],
        ),
    ]
