# Generated by Django 4.2.9 on 2024-01-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0006_cuadro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuadro",
            old_name="A",
            new_name="a",
        ),
        migrations.RenameField(
            model_name="cuadro",
            old_name="B",
            new_name="b",
        ),
        migrations.RenameField(
            model_name="cuadro",
            old_name="C",
            new_name="c",
        ),
    ]
