# Generated by Django 4.2.9 on 2024-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0007_rename_a_cuadro_a_rename_b_cuadro_b_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuadro",
            name="year",
            field=models.CharField(max_length=10),
        ),
    ]
