# Generated by Django 4.2.9 on 2024-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0008_alter_cuadro_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="art_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="culture_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="iq_score",
            field=models.IntegerField(default=0),
        ),
    ]
