# Generated by Django 4.2.9 on 2024-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "culturizateApp",
            "0009_userprofile_art_score_userprofile_culture_score_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="art_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="culture_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="iq_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
