# Generated by Django 4.2.9 on 2024-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0010_userprofile_art_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="art_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="art_success",
            field=models.IntegerField(default=0),
        ),
    ]
