# Generated by Django 4.2.9 on 2024-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0011_userprofile_art_errors_userprofile_art_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="art_attempts",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="culture_attempts",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="iq_attempts",
            field=models.IntegerField(default=2),
        ),
    ]
