# Generated by Django 4.2.9 on 2024-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0012_alter_userprofile_art_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="round",
            field=models.IntegerField(default=0),
        ),
    ]
