# Generated by Django 4.2.9 on 2024-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0014_userprofile_art_test_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="initial_score",
            field=models.IntegerField(default=0),
        ),
    ]
