# Generated by Django 4.2.9 on 2024-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0015_userprofile_initial_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sociedad_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sociedad_test_score",
            field=models.IntegerField(default=0),
        ),
    ]
