# Generated by Django 4.2.9 on 2024-01-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0016_userprofile_sociedad_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="sociedad_score",
            new_name="sociedad_actual_score",
        ),
    ]
