# Generated by Django 4.2.9 on 2024-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "culturizateApp",
            "0017_rename_sociedad_score_userprofile_sociedad_actual_score",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sociedad_last_score",
            field=models.IntegerField(default=0),
        ),
    ]
