# Generated by Django 4.2.9 on 2024-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culturizateApp", "0018_userprofile_sociedad_last_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sociedad_test_message",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
